### ISSUE TITLE
Later versions of pymongo is incompatible with dpimport

### ISSUE THREAD

**Issue by tashrifbillah** [AMP-SCZ/dpimport#11]
Currently, the `pymongo` version is open-ended:

https://github.com/AMP-SCZ/dpimport/blob/bbc6e09dd6eba518e8a075c4af3c9ade4c1f695d/setup.py#L6-L10

Which installs pymongo 4.0 and then `import.py` crashes into:

```
connecting to: mongodb://hi.hello.org:27019/dpdata?authSource=admin&compressors=disabled&gssapiServiceName=mongodb
Error: couldn't connect to server hi.hello.org:27019, connection attempt failed: SocketException: Error connecting to hi.hello.org:27019 (10.129.87.195:27019) :: caused by :: Connection refused :
connect@src/mongo/shell/mongo.js:372:17
@(connect):2:6
exception: connect failed
exiting with code 1
Traceback (most recent call last):
  File "miniconda3/envs/dpimport/bin/import.py", line 191, in <module>
    main()
  File "miniconda3/envs/dpimport/bin/import.py", line 36, in main
    db = Database(config, args.dbname).connect()
  File "miniconda3/envs/dpimport/lib/python3.10/site-packages/dpimport/database/__init__.py", line 25, in connect
    self.client = MongoClient(
  File "miniconda3/envs/dpimport/lib/python3.10/site-packages/pymongo/mongo_client.py", line 739, in __init__
    dict(common.validate(keyword_opts.cased_key(k), v) for k, v in keyword_opts.items())
  File "miniconda3/envs/dpimport/lib/python3.10/site-packages/pymongo/mongo_client.py", line 739, in <genexpr>
    dict(common.validate(keyword_opts.cased_key(k), v) for k, v in keyword_opts.items())
  File "miniconda3/envs/dpimport/lib/python3.10/site-packages/pymongo/common.py", line 754, in validate
    value = validator(option, value)
  File "miniconda3/envs/dpimport/lib/python3.10/site-packages/pymongo/common.py", line 159, in raise_config_error
    raise ConfigurationError("Unknown option %s" % (key,))
pymongo.errors.ConfigurationError: Unknown option ssl_cert_reqs
```

The [solution](https://github.com/apache/airflow/pull/20511) is to downgrade it to 3.11.4.

**Comment by tashrifbillah** [comment]
In the process, it was found that both `Pipfile` and `Pipefile.lock` are useless. So we are deleting them and effecting version specification in `setup.py`.
